### ISSUE TITLE
Mejorar consola de Evaluación

### ISSUE THREAD

**Issue by manugunther** [alexgadea/fun-gui#1]
La consola de evaluación debe mostrar de una forma lo más entendible posible cuáles son los pasos de evaluación, de acuerdo a cada comando.

Una idea podría ser:

Asumamos:
let fun f x = case x of
                          0 -> 0
                          _ -> 1
 
Dos posibilidades para el comando "step":

fun> step f@5
f@5
->
1

O:

fun> step f@5
f@5
->
case 5 of
   0 -> 0
   _ -> 1

fun> step
case 5 of
   0 -> 0
   _ -> 1

->

1

**Comment by miguelpagano** [comment]
Lo cierro porque ahora está implementada una de las opciones que mencionaba @manugunther al abrir este issue.

```
Modulo cargado

fun> step sum.[1,2,3

No hay expresión cargada

fun> load sum.[1,2,3]

Expresión cargadasum.succ 0▹(succ succ 0▹(succ succ succ 0▹[]))

fun> step

case [1,2,3] of
	y▹ys -> y+sum@ys
	[] -> 0


fun> step

1+sum@[2,3]

fun> step

1+case [2,3] of
	y▹ys -> y+sum@ys
	[] -> 0


fun> step

1+(2+sum@[3])

fun> step

1+(2+case [3] of
	y▹ys -> y+sum@ys
	[] -> 0
)

fun> step

1+(2+(3+sum@[]))

fun> step

1+(2+(3+case [] of
	y▹ys -> y+sum@ys
	[] -> 0
))

fun> step

1+(2+(3+0))

fun> step

1+(2+succ (2+0))

fun> step

1+(2+succ succ (1+0))

fun> step

1+(2+succ succ succ (0+0))

fun> step

1+(2+3)

fun> step

1+succ (1+3)

fun> step

1+succ succ (0+3)

fun> step

1+5

fun> step

succ (0+5)

fun> step

6
```
