### ISSUE TITLE
Guardar antes de compilar

### ISSUE THREAD

**Issue by alexgadea** [alexgadea/fun-gui#27]
Al darle al botón de compilar el archivo tiene que estar guardado de otra manera compila una versión vieja. Conclusión uno tiene que acordarse de guardar antes de compilar.

Cambio: Hacer que el mismo botón de compilar guarde antes.

**Comment by MaicoLeberle** [comment]
Cerrado por d7142a3354ba617d88dcc80850ab1b0d722ab9e1 .
