### ISSUE TITLE
Atajos de teclado para moverse en la pantalla

### ISSUE THREAD

**Issue by alexgadea** [alexgadea/fun-gui#28]
Sobre el menú (de la izquierda) de módulos cargados, ¿debería expandirse  automáticamente al compilar?

En un primer momento me parecía que estaba bueno, después de usarlo un rato largo me empezó a parecer que tal vez no hacía falta. ¿Tal vez se puede agregar una opción "tildeable" para configurar una u otra opción?

**Comment by miguelpagano** [comment]
Identificamos dos acciones distintas: 
1. moverse entre las distintas partes de la pantalla
2. mostrar/ocultar partes de la interfaz

Para moverse a un lugar de la interfaz utilizamos `Ctrl+k`, donde `k` está indicada en la captura de pantalla adjunta. 

Para mostrar/ocultar la parte correspondiente utilizamos `Ctrl+Shift+k`.
![fun-gui](https://cloud.githubusercontent.com/assets/769195/9452979/ca9ddc74-4a8d-11e5-8289-da07b1ed7d74.png)
