### ISSUE TITLE
Generar reglas con conmutatividad

### ISSUE THREAD

**Issue by alexgadea** [alexgadea/fun-gui#29]
Generar reglas con conmutatividad, como ya pasa para la asociatividad.
Por ejemplo, como axioma tenemos la regla "Neutro de la equivalencia a derecha" que aparece como

- (p ≡ True) ≡ p

el cual lo podemos usar para probar por ejemplo que p ≡ (True ≡ p), es decir con la asociatividad "para el otro lado". Por lo tanto la siguiente prueba es valida.

let thm testAsoc =  p ≡ (True ≡ p)
begin proof
    p
    ≡ { Neutro de la equivalencia a derecha }
    True ≡ p
end proof

**Comment by manugunther** [comment]
Esto no debería estar en "fun" en vez de "fun-gui"?

**Comment by alexgadea** [comment]
Cuanta verdad!
