### ISSUE TITLE
Atajos de teclado para símbolos

### ISSUE THREAD

**Issue by manugunther** [alexgadea/fun-gui#34]
Para poner símbolos unicode en una prueba debemos ir al panel con el mouse. Sería muy bueno poder hacer \equiv o \== por ejemplo como en agda, para introducir los símbolos.

**Comment by alexgadea** [comment]
Tal vez usar algo de [esto](https://developer.gnome.org/gtksourceview/stable/GtkSourceCompletion.html#GtkSourceCompletion.description) sea una buena idea. O sea, lo [tenemos](https://hackage.haskell.org/package/gtksourceview2-0.13.1.3/docs/Graphics-UI-Gtk-SourceView-SourceCompletion.html) para haskell solo que con poca documentación, por eso el primer link.

**Comment by miguelpagano** [comment]
@alexgadea  lo hizo: 607d07d696bcdd2c0a4782ff7ca3a94da668b203 y df5928080a82b2cbeb88b6ed99580ef3eb959776
