### ISSUE TITLE
Bug de validación

### ISSUE THREAD

**Issue by alexgadea** [alexgadea/fun-gui#37]
**Probablemente esto es un bug de Equ, pero la forma de probarlo
de momento es a partir de Fun.**

El bug me lo encontré armando teoremas nuevos que son
versiones de teoremas ya probados módulo AC. La versión
minimal podría ser algo así.

Supongamos tenemos probado el teorema

> let thm estrella = (p ∨ q ≡ p ∨ ¬q) ≡ p
> begin proof
> ...
> end proof

y queremos probar ahora el mismo teorema usando el ya probado,
pero donde tenemos los nombres de variable cambiados de forma
bien peculiar (y con un error, porque la ultima "p" debería ser una "q")

> let thm estrella2 = (q ∨ p ≡ q ∨ ¬p) ≡ p
> begin proof
>     (q ∨ p ≡ q ∨ ¬p) ≡ p
>     ≡ { estrella }
>     True
> end proof

Esa prueba no debería validar, **sin embargo lo hace**. Ahora si cambiamos
los nombres de variables por "frescos", digamos... (a ∨ b ≡ a ∨ ¬b) ≡ b. Entonces
la prueba no valida, como debería pasar.

**Comment by miguelpagano** [comment]
Este bug se encontraba en  Equ y @manugunther lo corrigió miguelpagano/equ@338637ea7497f3c3573f40d67c4110e1f0bc19ab
