### ISSUE TITLE
Herramientas gráficas para crear declaraciones

### ISSUE THREAD

**Issue by manugunther** [alexgadea/fun-gui#6]
Tener en el menú una forma de insertar declaraciones.
Por ejemplo:

Insertar especificación mostraría un cuadro donde el usuario puede ingresar el nombre de la función, el tipo, las variables y la expresión. Luego esa información se inserta en el texto.

Para las pruebas lo ideal sería poder importar la interfaz para pruebas que tenemos en equ, agregando  la posibilidad para pruebas por inducción y casos, pero esto puede llevar bastante tiempo...

**Comment by miguelpagano** [comment]
Esto se implementó pero lo eliminamos en 229084073680114e6fc59d08d6b25f8f6eb98fe5 Ahora cerramos este issue.
